services:
  postgres:
    image: postgres:15.7
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dealership
    ports:
      - '5432:5432'